"""
Secure token models stored in the database.

PasswordResetToken  — one-time token emailed to users for password reset
AdminInviteToken    — one-time token generated by admin to invite a new admin
"""
from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey
from sqlalchemy.sql import func
import uuid
from src.database import Base


class PasswordResetToken(Base):
    __tablename__ = "password_reset_tokens"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    token = Column(String, unique=True, nullable=False, index=True)
    is_used = Column(Boolean, default=False, nullable=False)
    expires_at = Column(DateTime, nullable=False)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)


class AdminInviteToken(Base):
    __tablename__ = "admin_invite_tokens"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    # Who generated this invite
    created_by_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    token = Column(String, unique=True, nullable=False, index=True)
    # Optional: lock the invite to a specific email address
    invited_email = Column(String, nullable=True)
    is_used = Column(Boolean, default=False, nullable=False)
    expires_at = Column(DateTime, nullable=False)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
