import secrets
import os
from datetime import datetime, timedelta, timezone
from fastapi import APIRouter, Depends, HTTPException, Request, Response, status
from sqlalchemy.orm import Session
from src.database import get_db
from src.models.user import User, UserRole
from src.models.token import PasswordResetToken, AdminInviteToken
from src.schemas.user import (
    UserCreate, UserLogin, UserResponse,
    ForgotPasswordRequest, ResetPasswordRequest,
)
from src.auth import verify_password, get_password_hash, create_access_token, get_current_user
from src.config import settings
from src import email_service

router = APIRouter(prefix="/api/auth", tags=["Authentication"])

COOKIE_NAME = "access_token"


def _is_production() -> bool:
    return bool(
        os.getenv("RENDER")
        or os.getenv("RAILWAY_ENVIRONMENT")
        or os.getenv("DYNO")
        or os.getenv("FLY_APP_NAME")
    )


def _set_auth_cookie(response: Response, token: str) -> None:
    response.set_cookie(
        key=COOKIE_NAME,
        value=token,
        httponly=True,
        secure=_is_production(),
        samesite="lax",
        max_age=settings.ACCESS_TOKEN_EXPIRE_MINUTES * 60,
        path="/",
    )


def _clear_auth_cookie(response: Response) -> None:
    response.delete_cookie(key=COOKIE_NAME, path="/")


# ── Register ───────────────────────────────────────────────────────────────────

@router.post("/register", response_model=UserResponse, status_code=status.HTTP_201_CREATED)
def register(
    request: Request,
    response: Response,
    user_data: UserCreate,
    db: Session = Depends(get_db),
):
    """
    Public registration for volunteer, field_worker, and admin (with invite token).

    - volunteer / field_worker: open registration, no token needed.
    - admin: requires a valid invite_token generated by the current admin.
      Only one admin is allowed at a time; the invite is single-use.

    Rate limited: 5 requests/minute per IP.
    """
    # ── Admin registration via invite token ───────────────────────────────────
    if user_data.role == UserRole.ADMIN:
        if not user_data.invite_token:
            raise HTTPException(
                status_code=400,
                detail="An invite token is required to register as admin. "
                       "Ask the current admin to generate one.",
            )

        now = datetime.now(timezone.utc)
        invite = (
            db.query(AdminInviteToken)
            .filter(AdminInviteToken.token == user_data.invite_token)
            .first()
        )

        if not invite:
            raise HTTPException(status_code=400, detail="Invalid invite token.")

        # Make expires_at timezone-aware for comparison
        expires_at = invite.expires_at
        if expires_at.tzinfo is None:
            expires_at = expires_at.replace(tzinfo=timezone.utc)

        if invite.is_used:
            raise HTTPException(status_code=400, detail="This invite token has already been used.")
        if expires_at < now:
            raise HTTPException(status_code=400, detail="This invite token has expired.")
        if invite.invited_email and invite.invited_email.lower() != user_data.email.lower():
            raise HTTPException(
                status_code=400,
                detail="This invite token was issued for a different email address.",
            )

        # Enforce single-admin rule
        existing_admin = db.query(User).filter(User.role == UserRole.ADMIN).first()
        if existing_admin:
            raise HTTPException(
                status_code=400,
                detail="An admin account already exists. "
                       "The current admin must transfer or delete their account first.",
            )

        # Mark invite as used
        invite.is_used = True

    # ── Volunteer / field_worker open registration ────────────────────────────
    existing = db.query(User).filter(User.email == user_data.email).first()
    if existing:
        raise HTTPException(status_code=400, detail="Email already registered.")

    new_user = User(
        email=user_data.email,
        full_name=user_data.full_name.strip(),
        hashed_password=get_password_hash(user_data.password),
        role=user_data.role,
        phone=user_data.phone,
        location=user_data.location,
    )
    db.add(new_user)
    db.commit()
    db.refresh(new_user)

    # Send welcome email (non-blocking — failure is logged, not raised)
    email_service.send_welcome_email(new_user.email, new_user.full_name, new_user.role.value)

    token = create_access_token(data={"sub": new_user.id, "role": new_user.role.value})
    _set_auth_cookie(response, token)
    return UserResponse.from_orm(new_user)


# ── Login ──────────────────────────────────────────────────────────────────────

@router.post("/login", response_model=UserResponse)
def login(
    request: Request,
    response: Response,
    credentials: UserLogin,
    db: Session = Depends(get_db),
):
    """
    Login with email and password. Sets a httpOnly cookie.
    Rate limited: 10 requests/minute per IP.
    """
    user = db.query(User).filter(User.email == credentials.email).first()
    if not user or not verify_password(credentials.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password.",
        )
    if not user.is_active:
        raise HTTPException(
            status_code=403,
            detail="Account is inactive. Contact your administrator.",
        )

    token = create_access_token(data={"sub": user.id, "role": user.role.value})
    _set_auth_cookie(response, token)
    return UserResponse.from_orm(user)


# ── Logout ─────────────────────────────────────────────────────────────────────

@router.post("/logout", status_code=status.HTTP_204_NO_CONTENT)
def logout(response: Response):
    """Clear the auth cookie. Safe to call even with an expired token."""
    _clear_auth_cookie(response)


# ── Session restore ────────────────────────────────────────────────────────────

@router.get("/me", response_model=UserResponse)
def get_me(current_user: User = Depends(get_current_user)):
    """
    Return the currently authenticated user from the database.
    Called on app load to restore session state from the httpOnly cookie.
    """
    return current_user


# ── Forgot password ────────────────────────────────────────────────────────────

@router.post("/forgot-password", status_code=200)
def forgot_password(
    data: ForgotPasswordRequest,
    db: Session = Depends(get_db),
):
    """
    Request a password reset email.

    Always returns 200 regardless of whether the email exists — this prevents
    user enumeration attacks (an attacker cannot tell if an email is registered).
    The reset link is valid for 1 hour and is single-use.
    """
    user = db.query(User).filter(User.email == data.email).first()

    if user and user.is_active:
        # Invalidate any existing unused tokens for this user
        db.query(PasswordResetToken).filter(
            PasswordResetToken.user_id == user.id,
            PasswordResetToken.is_used == False,  # noqa: E712
        ).update({"is_used": True})

        raw_token = secrets.token_urlsafe(48)
        expires_at = datetime.now(timezone.utc) + timedelta(
            minutes=settings.PASSWORD_RESET_EXPIRE_MINUTES
        )
        reset_token = PasswordResetToken(
            user_id=user.id,
            token=raw_token,
            expires_at=expires_at,
        )
        db.add(reset_token)
        db.commit()

        email_service.send_password_reset_email(user.email, user.full_name, raw_token)

    # Always return the same message — prevents email enumeration
    return {
        "message": "If that email is registered, a password reset link has been sent."
    }


# ── Reset password ─────────────────────────────────────────────────────────────

@router.post("/reset-password", status_code=200)
def reset_password(
    data: ResetPasswordRequest,
    db: Session = Depends(get_db),
):
    """
    Reset password using the token from the email link.
    The token is single-use and expires after 1 hour.
    """
    now = datetime.now(timezone.utc)

    reset_token = (
        db.query(PasswordResetToken)
        .filter(PasswordResetToken.token == data.token)
        .first()
    )

    if not reset_token:
        raise HTTPException(status_code=400, detail="Invalid or expired reset token.")

    expires_at = reset_token.expires_at
    if expires_at.tzinfo is None:
        expires_at = expires_at.replace(tzinfo=timezone.utc)

    if reset_token.is_used:
        raise HTTPException(status_code=400, detail="This reset link has already been used.")
    if expires_at < now:
        raise HTTPException(status_code=400, detail="This reset link has expired. Please request a new one.")

    user = db.query(User).filter(User.id == reset_token.user_id).first()
    if not user or not user.is_active:
        raise HTTPException(status_code=400, detail="Invalid or expired reset token.")

    user.hashed_password = get_password_hash(data.new_password)
    reset_token.is_used = True
    db.commit()

    return {"message": "Password reset successfully. You can now log in with your new password."}


# ── Validate invite token (used by frontend to pre-fill email) ─────────────────

@router.get("/validate-invite/{token}")
def validate_invite(token: str, db: Session = Depends(get_db)):
    """
    Check if an admin invite token is valid and return the invited email (if set).
    Called by the frontend when the register page loads with ?invite=<token>.
    """
    now = datetime.now(timezone.utc)
    invite = db.query(AdminInviteToken).filter(AdminInviteToken.token == token).first()

    if not invite:
        raise HTTPException(status_code=400, detail="Invalid invite token.")

    expires_at = invite.expires_at
    if expires_at.tzinfo is None:
        expires_at = expires_at.replace(tzinfo=timezone.utc)

    if invite.is_used:
        raise HTTPException(status_code=400, detail="This invite has already been used.")
    if expires_at < now:
        raise HTTPException(status_code=400, detail="This invite has expired.")

    return {
        "valid": True,
        "invited_email": invite.invited_email,
        "expires_at": invite.expires_at,
    }
